FROM php:7.1-alpine

LABEL maintainer="ipunkt Business Solutions <info@ipunkt.biz>"
LABEL version="php7.1-v2.0"
LABEL description="A supervisor configured to run with laravel artisan queue:work or artisan horizon command"

ENV PYTHON_VERSION=2.7.14-r2
ENV PY_PIP_VERSION=9.0.1-r1
ENV SUPERVISOR_VERSION=3.3.3

ENV QUEUE_CONNECTION=database
ENV QUEUE_NAME=default
ENV LARAVEL_HORIZON=false

# install basics and imap
RUN apk update \
    && apk add \
        bash \
        git \
        bzip2-dev \
        gettext-dev \
        openssl-dev \
        imap-dev \
    && docker-php-ext-configure imap --with-imap --with-imap-ssl \
    && docker-php-ext-install -j$(nproc) imap \
    && docker-php-ext-install pdo pdo_mysql pcntl posix             # Install pdo if you want to use database queue

# Install supervisor
RUN apk update && apk add -u python=$PYTHON_VERSION py-pip=$PY_PIP_VERSION
RUN pip install supervisor==$SUPERVISOR_VERSION

# Define working directory
WORKDIR /etc/supervisor/conf.d

# Use local configuration
COPY docker/worker/laravel-worker.conf.tpl /etc/supervisor/conf.d/laravel-worker.conf.tpl
#COPY laravel-horizon.conf.tpl /etc/supervisor/conf.d/laravel-horizon.conf.tpl

# Copy scripts
COPY docker/worker/init.sh /usr/local/bin/init.sh

#VOLUME /var/www/app
COPY . /data/www

RUN set -e -x \
    && mkdir -p storage/framework/cache \
    && mkdir -p storage/framework/views \
    && mkdir -p storage/framework/sessions \
    && chmod -R 777 storage

# Run supervisor
ENTRYPOINT ["/bin/sh", "/usr/local/bin/init.sh"]